# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Engram < Formula
  desc "Persistent memory for AI coding agents. Fork of Gentleman-Programming/engram with PostgreSQL, AWS RDS IAM, Azure Entra auth, and unaccent FTS."
  homepage "https://github.com/cloudopstudio/engram"
  version "1.15.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudopstudio/engram/releases/download/v1.15.13/engram_1.15.13_darwin_amd64.tar.gz"
      sha256 "0116cd20b842a1b63a1bf5f67f9c06a7a15f8e2e0479d62895c93fdcac95f57c"

      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudopstudio/engram/releases/download/v1.15.13/engram_1.15.13_darwin_arm64.tar.gz"
      sha256 "06d4ffdca7285046d687ca3f1ee6cfc997251637d8ca6827f6451460323a1054"

      define_method(:install) do
        bin.install "engram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudopstudio/engram/releases/download/v1.15.13/engram_1.15.13_linux_amd64.tar.gz"
      sha256 "5a672780ace06fab100c59a2a695de63193445684093a4d90458382140117015"
      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudopstudio/engram/releases/download/v1.15.13/engram_1.15.13_linux_arm64.tar.gz"
      sha256 "66cf08e19268f7b0f27e33d21bc463985ad3beacb618dfd082dc5eeb4e51b0d0"
      define_method(:install) do
        bin.install "engram"
      end
    end
  end

  test do
    system "#{bin}/engram", "--version"
  end
end
