# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Engram < Formula
  desc "Persistent memory for AI coding agents. Fork of Gentleman-Programming/engram with PostgreSQL, AWS RDS IAM, Azure Entra auth, and unaccent FTS."
  homepage "https://github.com/cloudopstudio/engram"
  version "1.20.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudopstudio/engram/releases/download/v1.20.1/engram_1.20.1_darwin_amd64.tar.gz"
      sha256 "3b9ccd10fdf70b8bf15aa6be69bbc4065ba4ce34752b66c41804cecb1b12a517"

      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudopstudio/engram/releases/download/v1.20.1/engram_1.20.1_darwin_arm64.tar.gz"
      sha256 "d9cd2285fc1aac85acdf955bc1b6c3f21f0ec1f4e6e65a92a35252eb525d8609"

      define_method(:install) do
        bin.install "engram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudopstudio/engram/releases/download/v1.20.1/engram_1.20.1_linux_amd64.tar.gz"
      sha256 "53c30fbae552a5c3b845501c032706860c8030b56d838914d14c8f4a4c7fe533"
      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudopstudio/engram/releases/download/v1.20.1/engram_1.20.1_linux_arm64.tar.gz"
      sha256 "34caad4125d23cea4583551d66deb59e8119216a77e1c8d17d645b814ce1704b"
      define_method(:install) do
        bin.install "engram"
      end
    end
  end

  test do
    system "#{bin}/engram", "--version"
  end
end
